name:           jailbreak-cabal
version:        1.3.2
synopsis:       Strip version restrictions from build dependencies in Cabal files.
author:
  - Peter Simons
  - Joel Taylor
  - Nikolay Amiantov
  - aszlig
maintainer:     Peter Simons <simons@cryp.to>
license:        BSD3
license-file:   LICENSE
github:         peti/jailbreak-cabal
category:       Distribution
stability:      stable
tested-with:    GHC > 7 && < 8.1
description:    Strip version restrictions from build dependencies in Cabal files.

ghc-options:    -Wall

dependencies:
  - base >= 3 && < 5
  - Cabal == 1.20.* || >= 1.23

executables:
  jailbreak-cabal:
    main:       Main.hs
